# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170530_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('W', 'waiting'), ('A', 'accepted'), ('R', 'refused')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('P', 'preparation'), ('D', 'development'), ('F', 'finished')], default='P', max_length=1),
        ),
    ]
