# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170603_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
