# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170625_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cv',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('W', 'waiting'), ('A', 'accepted'), ('R', 'refused')], default='W', max_length=1, null=True),
        ),
    ]
