# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20170626_0817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('project', 'user')]),
        ),
    ]
