# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170626_0838'),
        ('api', '0010_auto_20170626_1413'),
    ]

    operations = [
    ]
