# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170527_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='project',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
